### ISSUE TITLE
Updating existing model in Personality Insights

### ISSUE THREAD

**Issue by zacharynevin** [watson-developer-cloud/nodejs-wrapper#28]
Do you know how to update an existing model for personality insights? The Watson API documentation wasn't clear on this at all. The `contentItems` schema contains like 5 different ids and I don't know which one to use:
````
{
  "contentItems": [
    {
      "id": "",
      "userid": "",
      "sourceid": "",
      "created": "int",
      "updated": "int",
      "contenttype": "",
      "charset": "",
      "language": "",
      "content": "",
      "parentid": "",
      "reply": false,
      "forward": false
    }
  ]
}
````

**Comment by germanattanasio** [comment]
You are learn the input/output for each Watson service in the [swagger docs](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/apis/#!/personality-insights/profile)

ContentItem {
  id (string): Unique identifier for this content item.,
  userid (string): Unique identifier for the author of this content.,
  sourceid (string): Identifier for the source of this content. For example, blog123, twitter.,
  created (int, optional): Timestamp that identifies when this content was created. In milliseconds since midnight 1/1/1970 UTC.,
  updated (int, optional): Timestamp that identifies when this content was last updated. In milliseconds since midnight 1/1/1970 UTC.,
  contenttype (string): MIME type of the content, for example, "text/plain, text/html". The tags are stripped from HTML content before it is analyzed. Other MIME types are processed as is.,
  charset (string, optional): Character set of the text, for example, "UTF-8",
  language (string): Language identifier (two-letter ISO 639-1 identifier). Currently only English content (en) is supported.,
  content (string): Content to be analyzed. Up to 20MB of content is supported.,
  parentid (string, optional): Unique id of the parent content item. Used to identify hierarchical relationships between posts/replies, messages/replies, etc.,
  reply (boolean, optional): Indicates whether this content item is a reply to another content item.,
  forward (boolean, optional): Indicates whether this content item is a forwarded/copied version of another content item.
}

**Comment by zacharynevin** [comment]
I'm a dumbass
