### ISSUE TITLE
"API Version" parameter should be optional

### ISSUE THREAD

**Issue by jthomas** [watson-developer-cloud/nodejs-wrapper#40]
Users of the client library should be able to leave out the "version" parameter from the API calls and have the client library automatically use the latest version. It seems overkill to have every call specify this, most users will just want to use the current API version.

**Comment by jsstylos** [comment]
Hi jthomas, this is an issue we debated for a while. Unfortunately, supporting a default version parameter would mean that the addition of any new version would constitute a breaking change for the wrapper, since users' old code would try to use the new version and fail (version changes being not backwards compatible). We were unable to come up with a cleaner way of supporting regular version changes.

**Comment by germanattanasio** [comment]
We discussed this and the conclusion is that we prefer to ask for a version.
I'm closing the ticket.
