### ISSUE TITLE
Text to Speech service still using "beta" URL 

### ISSUE THREAD

**Issue by jthomas** [watson-developer-cloud/nodejs-wrapper#42]
https://github.com/watson-developer-cloud/nodejs-wrapper/blob/master/services/text_to_speech/v1.js#L26

  var serviceDefaults = {
    url: 'https://stream.watsonplatform.net/text-to-speech-beta/api',
    headers: {
      'content-type': 'application/json'
    }
  };

Watson API should now be: https://stream.watsonplatform.net/text-to-speech/api

**Comment by germanattanasio** [comment]
ohh, looks like when we merge the changes for concept_insights v2 they roll back other changes...

**Comment by germanattanasio** [comment]
I'll work on this. 
Thanks @jthomas!

**Comment by germanattanasio** [comment]
@jthomas `-beta` is there because we don't want to break existing apps. People that bound TTS or STT before the GA release should not be affected.  
We had the same issue with Tradeoff Analytics ( see #21). We will update the url when the Beta service is removed from Bluemix( 30 days after GA).  
In the meantime users need to specify `url: https://stream.watsonplatform.net/text-to-speech/api` when running locally. If they are using Bluemix, the wrapper gets `url` automatically from `VCAP_SERVICES`

I know this is a problem and we are thinking on alternatives on how to handle different releases + api versions. One option we are going to investigate is using the api version+release together so that the url is always the same.  
For example:
`https://stream.watsonplatform.net/text-to-speech/api/v1.experimental`
`https://stream.watsonplatform.net/text-to-speech/api/v1.beta`
`https://stream.watsonplatform.net/text-to-speech/api/v1`
`https://stream.watsonplatform.net/text-to-speech/api/v1.beta2`

**Comment by jthomas** [comment]
Okay, this should probably be documented.

**Comment by germanattanasio** [comment]
Our [examples](https://github.com/watson-developer-cloud/nodejs-wrapper/tree/master/examples) and the [readme](https://www.npmjs.com/package/watson-developer-cloud#speech-to-text) have examples where the `url` is begin specified.  
Where do you think we need to add this documentation? our ibm.com site ?
Thanks for the feedback anyway.

**Comment by jthomas** [comment]
Aw, I hadn't seen that. Looks fine.
